language: node_js

node_js:
  - "12"

cache:
  directories:
    - node_modules

script:
  - yarn test

deploy:
  provider: heroku
  api_key:
    secure: Fmf1zChv6cLgoVgNBAZTA0dR6+8LJ1vXMNeBDBdbqQNIweWXODe2mlWjRM4l/SAz9b4JSWChKn+Od8eaugfgs1xc9OoQZPG80pLKlDQ2rlZkXfFY/cI9+eGwvIDcBCUkDfxAFCLh1kSD48HZV5x0e7DBihnkI7AFRuP6wQoPjHI4jR7pNf7mn0Cfmwnd37V220+sdZEZm5TldX7PCyfFzm2+6iurXCUk7qqrJ//BvQ2VNzsNt8uSMDxeUEGQOpHOL70jt+pV1xCcpyGYEVTQgQPmdRARoj14dDME9cVf8A9WWOXNzG8Y03Sgs2WueKKSqGzNeGIDvBeT6llSHtHAgW89UasiSu+yYvAlDIeveNb0KIbepPFPXK0EGfBpafyyh/X6g8VlmqpBAh7ibQ4BlQZ1uIBm2wx2Bkd/BkmhL7FbOu+uqDD8ZK4VGv8KCH2AoqxZB4SjNP9dkV24SYYW8S748iipL96DZXmDe70sQKwm0kXM8GcrWulvUNthVo2Gf6P+fzOpSTUXux9L9MqrjlW9NIhU9aiJZcQ1WHh6/ehkneAkDkLpsvPIMBDErwTpciJtCQopwjS8ckfR48nG3ooXUEcLw5p5NnjJZxwo9/VkccRnU0AJ/bYMuce4StaR/2UkElIgeoBBWneK3OT0xIRCrIFXJM6Q+2T+xQF/J6M=
  app: moxy-proxy
  on:
    branch: master